### ISSUE TITLE
Inspections for identifier names in SnakemakeSL

### ISSUE THREAD

**Issue by nekit-000000** [JetBrains-Research/snakecharm#215]
In Snakemake spaces are cut from wildcard names, so this code is valid:
```
rule NAME:
    input: "{     sample     }.txt"
```
Lets have an inspection for this in SnakemakeSL.
For example, if you have this code:
```
rule NAME:
    input: "{       sample       }".txt
```
The name ` '       sample       '` will be highlighted as warning and a quick fix, that cuts spaces, will be offered.
And if you have this code:
```
rule NAME:
    shell: "{       foo       }".txt
```
The name `'     foo     '` will be highlighted as error with message: 

>  '    foo   ' is not a valid identifier name

**Comment by iromeo** [comment]
Technically you are right, but in real life, it is hard to imagine that someone needs `     sample     ` wildcard, e.g. you cannot use it after `wildcards.` because will be `wildcards.     sample     ` which is likely doesn't work both in python and injection code. 

Let's treat it as error:
![image](https://user-images.githubusercontent.com/72933/64046507-ac5e0b00-cb74-11e9-914d-b5af2c444593.png)
