### ISSUE TITLE
Unused log file quick fix

### ISSUE THREAD

**Issue by dakochik** [JetBrains-Research/snakecharm#452]
1. Fix behavior with triple quoted string
2. Update fix text e.g. from `shell: "..."` to `shell: "(...) >{log} 2>&1"`

**Comment by iromeo** [comment]
1) Works wrong for string concatenation via '+':

```
    
rule rule_453_4:
    log: "aa"
    shell: 
        "foo boo" +
         "foo boo" +
        "-foo - boo"
 ```
 I suggest here show warning, but do not allow quickfix. Here user could write with '+' just several strings one after another
 
 2) Works incorrect for f-strings, because escaping is required (e.g like `{{log}}`)
```
 rule rule_453_51:
    log: "aa"
    shell:
        "foo boo"
        f"-foo - boo"
 ```
 
 3) Results in syntax errors:
 ```
 rule rule_453_52:
    log: "aa"
    shell:
        f"foo boo"
        "-foo - boo"
        
```

4) For
```
rule rule_453_2:
    log: "aa"
    shell: """
ddd bb
ddd bb
"""
```

will be nice to have:

```
rule rule_453_2:
    log: "aa"
    shell: """(
ddd bb
ddd bb
) >{log} 2>&1 """
```

instead of
```

rule rule_453_2:
    log: "aa"
    shell: """
    (
ddd bb
ddd bb
) >{log} 2>&1 """
```
